import pandas as pd
old = pd.read_csv(r'D:\CLC\project\results\drugclip_m4_candidate_screen_v01\ranked_candidates.csv')
new = pd.read_csv(r'D:\CLC\project\results\drugclip_science2026\family_aug_v01\m4_library_famaug_ranking.csv')
new_of = dict(zip(new.molecule, new['rank']))
old['new_rank'] = old.canonical_smiles.map(new_of)
hit = old.dropna(subset=['new_rank'])
print('old-200 found in new library: %d' % len(hit))
print('of those, new top500: %d  top1000: %d  top3000: %d' % ((hit.new_rank <= 500).sum(), (hit.new_rank <= 1000).sum(), (hit.new_rank <= 3000).sum()))
print('new-rank median of old candidates: %.0f / 28519' % hit.new_rank.median())
old_top50 = old.head(50).dropna(subset=['new_rank'])
print('old top50 -> new-rank median %.0f, in new top1000: %d/50' % (old_top50.new_rank.median(), (old_top50.new_rank <= 1000).sum()))
print()
print('new top10 (famaug ensemble):')
print(new.head(10)[['rank', 'molecule']].to_string(index=False))
