name: pacer_dc_geom2vec
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch>=2.2
  - numpy>=1.26
  - scipy
  - mdanalysis>=2.9
  - mdtraj>=1.10
  - pip
  - pip:
      - torch-geometric>=2.6
      - git+https://github.com/dinner-group/geom2vec.git@371d642ec1061664f16e49fcac702d07fc8d0b51
